name: Build Package

on:
  push:
    # tags:
      # - 'v2.1.10'
    branches:
       - 'main'

jobs:
  Build-And-Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build the project
        run: dotnet build --configuration Release --no-restore
      - name: Test the project
        run: dotnet test --no-build --verbosity normal
      - name: Pack the project
        run: dotnet pack --configuration Release --no-build -o ./nupkg
      - name: Push to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
